### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [Maximilian92/T02-Tool-path-planning-on-5-axis-machining-center-using-DRL#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. It looks very cool. Thank-you.

**Comment by Maximilian92** [comment]
> Hello, under what license is this project released under ? I would like to study it to learn from it. It looks very cool. Thank-you.

Hi, so sorry for the long time abscense. I've creaeted a new branch with license Apache v2. Have fun with the project if it's still in need.

**Comment by suprafun** [comment]
Thank you so very, very much. This is such a useful learning resource. Thank you again.

**Comment by Maximilian92** [comment]
> Thank you so very, very much. This is such a useful learning resource. Thank you again.

With pleasure :)
